<?php
require_once("../config/db_con.php");

// Create invoices table
$createMockData = "
CREATE TABLE IF NOT EXISTS mock_data (
    id INT AUTO_INCREMENT PRIMARY KEY,
    costOfGoodsSoldForGross INT(8) NOT NULL,
    population INT(8) NOT NULL,
    targetMarketPercentage INT(8) NOT NULL,
    benefits INT(8) NOT NULL,
    costs INT(8) NOT NULL,
    averageMonthlyRevenuePerUser INT(8) NOT NULL,
    averageUserLifespanInMonths INT(8) NOT NULL,
    grossMargin INT(8) NOT NULL,
    profit INT(8) NOT NULL,
    percentChangeInQuantityDemanded INT(8) NOT NULL,
    percentChangeInPrice INT(8) NOT NULL,
    sellingPrice INT(8) NOT NULL,
    variableCost INT(8) NOT NULL,
    marketingCosts INT(8) NOT NULL,
    numberOfNewCustomers INT(8) NOT NULL,
    clv INT(8) NOT NULL,
    averageRetention INT(8) NOT NULL,
    numberOfLostCustomers INT(8) NOT NULL,
    totalNumberOfCustomers INT(8) NOT NULL,
    yourCompanyMetric INT(8) NOT NULL,
    industryMetric INT(8) NOT NULL,
    revenue INT(8) NOT NULL,
    costOfGoodsSold INT(8) NOT NULL,
    totalRevenue INT(8) NOT NULL,
    numberOfOrders INT(8) NOT NULL,
    marketingSpend INT(8) NOT NULL,
    retainedCustomers INT(8) NOT NULL,
    initialCustomers INT(8) NOT NULL,
    percentPromoters INT(8) NOT NULL,
    percentDetractors INT(8) NOT NULL,
    completedActions INT(8) NOT NULL,
    totalVisitors INT(8) NOT NULL,
    percentSatisfied INT(8) NOT NULL,
    percentDissatisfied INT(8) NOT NULL,
    revenueFromAds INT(8) NOT NULL,
    costOfAdSpend INT(8) NOT NULL,
    totalClicks INT(8) NOT NULL,
    numberOfUsers INT(8) NOT NULL,
    cac INT(8) NOT NULL,
    averageInventoryValue INT(8) NOT NULL,
    ordersWithDefects INT(8) NOT NULL,
    totalOrders INT(8) NOT NULL,
    numberOfEmployees INT(8) NOT NULL,
    operatingIncome INT(8) NOT NULL,
    depreciationAmortization INT(8) NOT NULL,
    cashFromOperations INT(8) NOT NULL,
    capitalExpenditures INT(8) NOT NULL,
    totalLiabilities INT(8) NOT NULL,
    totalShareholdersEquity INT(8) NOT NULL,
    TotalCosts INT(8) NOT NULL,
    TotalNumberOfNewCustomers INT(8) NOT NULL,
    percentSatisfiedCustomers INT(8) NOT NULL,
    percentDissatisfiedCustomers INT(8) NOT NULL,
    yourCompanyConversionRate INT(8) NOT NULL,
    industryAverageConversionRate INT(8) NOT NULL,
    customerLifetimeValue INT(8) NOT NULL,
    customerAcquisitionCost INT(8) NOT NULL,
    totalRevenueForPeriod INT(8) NOT NULL,
    numberOfUsersForPeriod INT(8) NOT NULL,
    completedPurchasesFromEmail INT(8) NOT NULL,
    totalEmailClicks INT(8) NOT NULL
)";

mysqli_query($con, $createMockData) or die(mysqli_error($con));
echo json_encode("Tables created successfully.");
?>